apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-care-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: node
  template:
    metadata:
      name: node
      labels:
        k8s-app: node
    spec:
      containers:
        - name: node
          image: normie/customer-care-app:v1
          env:
            - name: DB2_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: db_conn_str
                  key: token
                  optional: false
      restartPolicy: Always
